### ISSUE TITLE
Erro no parsing

### ISSUE THREAD

**Issue by will76** [guilhermecgs/ir#1]
Primeiramente parabéns pela excelente ideia do projeto.

Meu "busca_tardes_e_faz_merge_operacoes" está retornando o seguinte erro que acredito ser de parsing(estou meio sem tempo pra olhar o código então estou abrindo essa issue)

```
DevTools listening on ws://127.0.0.1:5277/devtools/browser/6d52fa1e-2f52-4612-83e6-e3cb4d52f03e
[0228/180544.403:INFO:CONSOLE(0)] "Application Cache API manifest selection is deprecated and will be removed in M82, around April 2020. See https://www.chromestatus.com/features/6192449487634432 for more details.", source:  (0)
[0228/180544.409:INFO:CONSOLE(0)] "Creating Application Cache with manifest https://cei.b3.com.br/CEI_Responsivo/manifest/cei.appcache", source: https://cei.b3.com.br/CEI_Responsivo/ (0)
[0228/180544.412:INFO:CONSOLE(0)] "Application Cache Checking event", source: https://cei.b3.com.br/CEI_Responsivo/ (0)
[0228/180544.687:INFO:CONSOLE(0)] "Application Cache Error event: Manifest fetch failed (404) https://cei.b3.com.br/CEI_Responsivo/manifest/cei.appcache", source: https://cei.b3.com.br/CEI_Responsivo/ (0)
[0228/180601.151:INFO:CONSOLE(0)] "Application Cache API manifest selection is deprecated and will be removed in M82, around April 2020. See https://www.chromestatus.com/features/6192449487634432 for more details.", source:  (0)
[0228/180601.322:INFO:CONSOLE(0)] "Creating Application Cache with manifest https://cei.b3.com.br/CEI_Responsivo/manifest/cei.appcache", source: https://cei.b3.com.br/CEI_Responsivo/home.aspx (0)
[0228/180601.354:INFO:CONSOLE(0)] "Application Cache Checking event", source: https://cei.b3.com.br/CEI_Responsivo/home.aspx (0)
[0228/180601.370:INFO:CONSOLE(0)] "Application Cache Error event: Manifest fetch failed (404) https://cei.b3.com.br/CEI_Responsivo/manifest/cei.appcache", source: https://cei.b3.com.br/CEI_Responsivo/home.aspx (0)
[0228/180602.914:INFO:CONSOLE(0)] "Application Cache API manifest selection is deprecated and will be removed in M82, around April 2020. See https://www.chromestatus.com/features/6192449487634432 for more details.", source:  (0)
[0228/180602.982:INFO:CONSOLE(0)] "Creating Application Cache with manifest https://cei.b3.com.br/CEI_Responsivo/manifest/cei.appcache", source: https://cei.b3.com.br/CEI_Responsivo/negociacao-de-ativos.aspx (0)
[0228/180602.999:INFO:CONSOLE(0)] "Application Cache Checking event", source: https://cei.b3.com.br/CEI_Responsivo/negociacao-de-ativos.aspx (0)
[0228/180603.000:INFO:CONSOLE(0)] "Application Cache Error event: Manifest fetch failed (404) https://cei.b3.com.br/CEI_Responsivo/manifest/cei.appcache", source: https://cei.b3.com.br/CEI_Responsivo/negociacao-de-ativos.aspx (0)
Traceback (most recent call last):
  File ".\ir.py", line 81, in <module>
    main(sys.argv[1:])
  File ".\ir.py", line 26, in main
    do_busca_trades_e_faz_merge_operacoes()
  File ".\ir.py", line 43, in do_busca_trades_e_faz_merge_operacoes
    df_cei = crawler_cei.busca_trades()
  File "C:X\ir-master\src\crawler_cei.py", line 32, in busca_trades
    raise ex
  File "C:\X\ir-master\src\crawler_cei.py", line 28, in busca_trades
    self.__abre_consulta_trades()
  File "C:\ir-master\src\crawler_cei.py", line 64, in __abre_consulta_trades
    ddlAgentes.select_by_value('3')
  File "C:\X\Local\Programs\Python\Python36-32\lib\site-packages\selenium\webdriver\support\select.py", line 87, in select_by_value
    raise NoSuchElementException("Cannot locate option with value: %s" % value)
selenium.common.exceptions.NoSuchElementException: Message: Cannot locate option with value: 3
```

**Comment by guilhermecgs** [comment]
@will76 , muito provavelmente o erro eh porque a sua corretora nao é a XP.

Ness exato trecho de codigo, como nao tinha mais ninguem usando eu coloquei  hardcoded o codigo (XP->3) das corretoras que eu uso.

Entra no site do CEI manualmente e verifica o codigo da corretora que vc usa por favor que eu posso bolar um jeito de deixar generico.

**Comment by will76** [comment]
Resolvido colocando o código da minha corretora hardcoded.

(Solução não muito boa pra deixar genérico: variável com tabela de-para?)

**Comment by guilhermecgs** [comment]
Vou pensar em pegar todas as opcoes do combobox e fazer um loop em todas as corretoras.
