### ISSUE TITLE
Arquivo inicial no dropbox

### ISSUE THREAD

**Issue by eduneris71** [guilhermecgs/ir#17]
Olá Guilherme.
Encontrei seu projeto e gostaria de fazer uso, e quem sabe contribuir se meu nivel permitir. Encontrei o seguinte erro ao executar pela primeira vez. Saberia o motivo? Tenho um arquivo no dropbox que não possui dados nenhum. (um caracter para não dizer que está vazio). Esperava que ele fosse substituido por um arquivo atualizado do CEI, mas parece que ele está dando erro nesse ponto. Ou estou fazendo algo errado antes de executar pela primeira vez.
Segue a msg de erro.

"PS D:\Nuvem\OneDrive\Financas\Imposto_de_Renda\IR_MASTER\ir-master> python ./ir.py --do busca_trades_e_faz_merge_operacoes

DevTools listening on ws://127.0.0.1:60205/devtools/browser/1c5d60e8-0392-43fd-992e-32ee9df35a15
[0502/202720.682:ERROR:gpu_init.cc(426)] Passthrough is not supported, GL is swiftshader
Traceback (most recent call last):
  File "./ir.py", line 77, in <module>
    main(sys.argv[1:])
  File "./ir.py", line 25, in main
    do_busca_trades_e_faz_merge_operacoes()
  File "./ir.py", line 48, in do_busca_trades_e_faz_merge_operacoes
    df = merge_operacoes(df, df_cei)
  File "D:\Nuvem\OneDrive\Financas\Imposto_de_Renda\IR_MASTER\ir-master\src\stuff.py", line 154, in merge_operacoes
    if not len(df) and not len(other_df):
TypeError: object of type 'NoneType' has no len()
PS D:\Nuvem\OneDrive\Financas\Imposto_de_Renda\IR_MASTER\ir-master>"

**Comment by guilhermecgs** [comment]
@eduneris71 , o dataframe entrou na funcao como nulo.
Isso significa que ou o dados lidos do CEI estao errados ou o arquivo do dropbox esta errado.

Eu recomendo vc deletar o arquivo do dropbox se ele estiver sem nenhum trade ainda.

Adicionalmente acabei de inserir uma linha de validacao na funcao para descobrir qual dataframe esta vindo errado no seu caso. Muito provavelmente é o do CEI.

Se tiver condicoes, rode o programa em modo debug e va olhando
