### ISSUE TITLE
DownloadError('path', LookupError('not_found', None)

### ISSUE THREAD

**Issue by will76** [guilhermecgs/ir#2]
Quando rodo o _busca_trades_e_faz_merge_operacoes_ estou recebendo a seguinte mensagem. Retirei a chamada da variável em _dbx.files_download_to_file_ pra ficar testando e até agora não consegui acertar. Nessas mudanças recebi também o erro 'malformed_path'.

Como deve ser o formato do caminho especificado? Ele pode apontar pra qualquer pasta dentro do Dropbox?

```
[0302/095639.279:INFO:CONSOLE(0)] "Application Cache Checking event", source: https://cei.b3.com.br/CEI_Responsivo/negociacao-de-ativos.aspx (0)
[0302/095639.312:INFO:CONSOLE(0)] "Application Cache Error event: Manifest fetch failed (404) https://cei.b3.com.br/CEI_Responsivo/manifest/cei.appcache", source: https://cei.b3.com.br/CEI_Responsivo/negociacao-de-ativos.aspx (0)
Traceback (most recent call last):
  File ".\ir.py", line 81, in <module>
    main(sys.argv[1:])
  File ".\ir.py", line 26, in main
    do_busca_trades_e_faz_merge_operacoes()
  File ".\ir.py", line 46, in do_busca_trades_e_faz_merge_operacoes
    download_dropbox_file()
  File "C:\Users\X\Dropbox\X\ir-master\src\dropbox_files.py", line 11, in download_dropbox_file
    dbx.files_download_to_file(OPERATIONS_FILEPATH,'/Apps')
  File "C:\Users\X\AppData\Local\Programs\Python\Python36-32\lib\site-packages\dropbox\base.py", line 1238, in files_download_to_file
    None,
  File "C:\Users\X\AppData\Local\Programs\Python\Python36-32\lib\site-packages\dropbox\dropbox.py", line 296, in request
    user_message_locale)
dropbox.exceptions.ApiError: ApiError('1b103089b3d2c6617dad9ddfdce21cc1', DownloadError('path', LookupError('not_found', None)))
```

**Comment by guilhermecgs** [comment]
Coloquei uns exemplos no README

**Comment by will76** [comment]
@guilhermecgs Não consigo de jeito nenhum, dá o mesmo erro. Acabei debugando e colocando o resultado do crawler no txt na mão, depois excluí todas as chamadas do dropbox.

**Comment by guilhermecgs** [comment]
Cara, muito estranho.
Eu iria verificar a sua API_KEY do dropbox.
Existe um teste unitário especifico para isso, sugiro vc executar e testar.

No geral, essa API do dropbox sempre funcionou de primeira comigo.

Se voce estiver tentando baixar o arquivo, outra sugestao é criar o arquivo manualmente na primeira execucao. Pode ser que exista um descasamento e o codigo espera que o arquivo ja exista e nao tente cria-lo antes.
